src/Entity/Mapper.php
<?php

namespace App\Entity;

use App\Repository\MapperRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MapperRepository::class)]
class Mapper
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    private ?int $id;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $display_name;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $account_created;

    #[ORM\Column(type: 'integer')]
    private ?int $changesets_count;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $status;

    /** @var Collection<int,Changeset> */
    #[ORM\OneToMany(targetEntity: Changeset::class, mappedBy: 'mapper', orphanRemoval: true)]
    private Collection $changesets;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $image;

    /** @var Collection<int,Note> */
    #[ORM\OneToMany(targetEntity: Note::class, mappedBy: 'mapper', orphanRemoval: true)]
    private Collection $notes;

    #[ORM\OneToOne(targetEntity: Welcome::class, mappedBy: 'mapper', cascade: ['persist'])]
    private ?Welcome $welcome;

    /** @var Collection<int,Region> */
    #[ORM\ManyToMany(targetEntity: Region::class, inversedBy: 'mappers')]
    private Collection $region;

    public function __construct()
    {
        $this->changesets = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->region = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getAccountCreated(): ?\DateTimeInterface
    {
        return $this->account_created;
    }

    public function setAccountCreated(\DateTimeInterface $account_created): self
    {
        $this->account_created = $account_created;

        return $this;
    }

    public function getChangesetsCount(): ?int
    {
        return $this->changesets_count;
    }

    public function setChangesetsCount(int $changesets_count): self
    {
        $this->changesets_count = $changesets_count;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int,Changeset>
     */
    public function getChangesets(): Collection
    {
        return $this->changesets;
    }

    public function addChangeset(Changeset $changeset): self
    {
        if (!$this->changesets->contains($changeset)) {
            $this->changesets[] = $changeset;
            $changeset->setMapper($this);
        }

        return $this;
    }

    public function removeChangeset(Changeset $changeset): self
    {
        // set the owning side to null (unless already changed)
        if ($this->changesets->removeElement($changeset) && $changeset->getMapper() === $this) {
            $changeset->setMapper(null);
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int,Note>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setMapper($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        // set the owning side to null (unless already changed)
        if ($this->notes->removeElement($note) && $note->getMapper() === $this) {
            $note->setMapper(null);
        }

        return $this;
    }

    public function getFirstChangeset(): Changeset
    {
        $changesets = $this->changesets->toArray();

        $createdAt = array_map(static fn (Changeset $changeset): ?\DateTimeImmutable => $changeset->getCreatedAt(), $changesets);

        array_multisort($createdAt, \SORT_ASC, $changesets);

        return $changesets[0];
    }

    public function getWelcome(): ?Welcome
    {
        return $this->welcome;
    }

    public function setWelcome(Welcome $welcome): self
    {
        // set the owning side of the relation if necessary
        if ($welcome->getMapper() !== $this) {
            $welcome->setMapper($this);
        }

        $this->welcome = $welcome;

        return $this;
    }

    /**
     * @return Collection<int, Region>
     */
    public function getRegion(): Collection
    {
        return $this->region;
    }

    public function addRegion(Region $region): self
    {
        if (!$this->region->contains($region)) {
            $this->region->add($region);
        }

        return $this;
    }

    public function removeRegion(Region $region): self
    {
        $this->region->removeElement($region);

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Table(name: 'users')]
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    private int $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private string $display_name;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see Symfony\Component\Security\Core\User\UserInterface
     */
    public function getUserIdentifier(): string
    {
        return $this->display_name;
    }

    /**
     * @see Symfony\Component\Security\Core\User\UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * This method can be removed in Symfony 6.0 - is not needed for apps that do not check user passwords.
     *
     * @see Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return null;
    }

    /**
     * This method can be removed in Symfony 6.0 - is not needed for apps that do not check user passwords.
     *
     * @see Symfony\Component\Security\Core\User\UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see Symfony\Component\Security\Core\User\UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Controller/App/ListController.php
<?php

namespace App\Controller\App;

use App\Entity\Mapper;
use App\Service\RegionsProvider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ListController extends AbstractController
{
    public function __construct(
        private readonly RegionsProvider $provider,
    ) {
    }

    #[Route('/{regionKey}', name: 'app_region', requirements: ['regionKey' => '[\w\-_]+'])]
    public function redirectToList(string $regionKey): Response
    {
        return $this->redirectToRoute('app_list', ['regionKey' => $regionKey]);
    }

    #[Route('/{regionKey}/list/{year}/{month}', name: 'app_list', requirements: ['regionKey' => '[\w\-_]+'])]
    #[Route('/{continent}/{regionKey}/list/{year}/{month}', name: 'app_list_full', requirements: ['continent' => 'asia|africa|australia|europe|north-america|south-america', 'regionKey' => '[\w\-_]+'])]
    public function index(string $regionKey, ?string $continent, ?int $year = null, ?int $month = null): Response
    {
        $region = $this->provider->getRegion($continent, $regionKey);
        $regionEntity = $this->provider->getEntity($regionKey);
        $region['lastUpdate'] = null === $regionEntity ? null : $regionEntity->getLastUpdate();
        $region['count'] = $this->provider->getPercentage($regionKey);

        if (null === $year && null === $month) {
            $year = (int) date('Y');
            $month = (int) date('m');
        }

        if ($month > 12) {
            $year = $year + 1;
            $month = 1;

            return $this->redirectToRoute('app_list_full', ['continent' => $region['continent'], 'regionKey' => $region['key'], 'year' => $year, 'month' => $month]);
        } elseif ($month < 1) {
            $year = $year - 1;
            $month = 12;

            return $this->redirectToRoute('app_list_full', ['continent' => $region['continent'], 'regionKey' => $region['key'], 'year' => $year, 'month' => $month]);
        }

        $mappers = null === $regionEntity ? [] : $regionEntity->getMappers()->toArray();

        if (\count($mappers) > 0) {
            $firstChangetsetCreatedAt = array_map(fn (Mapper $mapper): ?\DateTimeImmutable => $mapper->getFirstChangeset()->getCreatedAt(), $mappers);
            array_multisort($firstChangetsetCreatedAt, \SORT_DESC, $mappers);

            $month = (new \DateTime())->setDate($year, $month, 1);

            $mappers = array_filter(
                $mappers,
                function (Mapper $mapper) use ($month): bool {
                    /** @var \DateTimeImmutable */
                    $createdAt = $mapper->getFirstChangeset()->getCreatedAt();

                    return $createdAt->format('Ym') === $month->format('Ym');
                }
            );
        }

        return $this->render('app/list/index.html.twig', [
            'region' => $region,
            'mappers' => $mappers,
            'month' => $month,
        ]);
    }
}

templates/app/list/avatar.html.twig
<div class="flex items-center">
    {% if mapper.image is not null %}
    <img class="inline-block h-9 w-9 rounded-full border" src="{{ mapper.image }}"
        alt="{{ mapper.displayName }} profile picture">
    {% else %}
    <img class="inline-block h-9 w-9 rounded-full border" src="{{ asset('build/images/avatar_large.png') }}"
        alt="Default profile picture">
    {% endif %}
    <div class="max-w-xs ml-3">
        <p class="text-sm font-medium text-gray-700 group-hover:text-gray-900 text-ellipsis overflow-hidden">
            {{ mapper.displayName }}
        </p>
        {% if app.user is not null %}
        <p class="text-xs font-medium text-gray-500 group-hover:text-gray-700">
            {{ 'View profile'|trans }}
        </p>
        {% endif %}
    </div>
</div>

templates/app/list/chart.html.twig
<div id="chart-stats" class="h-full w-full" data-continent="{{ region.continent }}" data-region="{{ region.key }}" data-series1="{{ 'Not welcomed yet'|trans }}"
  data-series2="{{ 'Welcomed'|trans }}"></div>

templates/app/list/header.html.twig
<header>
    <div class="sm:flex sm:items-center sm:justify-between">
        <div>
            <h1 class="text-2xl font-bold text-gray-900">{{ 'Mappers'|trans }}</h1>
            <p class="text-sm font-medium text-gray-500">
                {{ 'List of mappers that have their first edit in the region'|trans }}
            </p>
        </div>
        <div class="mt-3 flex items-center sm:mt-0 sm:ml-4">
            <div class="mr-5">
                {{ month|format_date(pattern='MMMM yyyy') }}
            </div>

            <span class="relative z-0 inline-flex shadow-sm rounded-md">
                {% set prev_month = (month|date('m')) - 1 %}
                {% set prev_year = (month|date('Y')) %}
                <a class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                    href="{{ path('app_list_full', {continent: region.continent, regionKey: region.key, year: prev_year, month: prev_month}) }}">
                    <span class="sr-only">{{ 'Previous month'|trans }}</span>
                    <!-- Heroicon name: solid/chevron-left -->
                    <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                        aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                            clip-rule="evenodd" />
                    </svg>
                </a>
                {% set next_month = (month|date('m')) + 1 %}
                {% set next_year = (month|date('Y')) %}
                {% if (next_year > (date()|date('Y'))) or (next_year == (date()|date('Y')) and next_month > (date()|date('m'))) %}
                <span class="-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500 opacity-50 cursor-not-allowed">
                    <span class="sr-only">{{ 'Next month'|trans }}</span>
                    <!-- Heroicon name: solid/chevron-right -->
                    <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                        aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                            clip-rule="evenodd" />
                    </svg>
                </span>
                {% else %}
                <a class="-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                    href="{{ path('app_list_full', {continent: region.continent, regionKey: region.key, year: next_year, month: next_month}) }}">
                    <span class="sr-only">{{ 'Next month'|trans }}</span>
                    <!-- Heroicon name: solid/chevron-right -->
                    <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                        aria-hidden="true">
                        <path fill-rule="evenodd"
                            d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                            clip-rule="evenodd" />
                    </svg>
                </a>
                {% endif %}
            </span>
        </div>
    </div>
</header>

templates/app/list/index.html.twig
{% extends 'app/layout.html.twig' %}

{% block title %}{{ region.flag }} {{ region.name }} - {{ welcome.title }}{% endblock %}

{% block content %}

<div class="flex h-48">
    {{ include('app/list/map.html.twig') }}
    {{ include('app/list/chart.html.twig') }}
</div>

<div class="mt-5">
    {{ include('app/list/header.html.twig') }}
</div>

<main class="mt-5">
    <div class="flex justify-between mb-3 text-sm text-gray-600">
        <div>
            {{ '{count} new mappers ({percent} %) have already been welcomed'|trans({'{count}': region.count.count, '{percent}': region.count.percentage}) }}
        </div>
        {% if region.lastUpdate is not null %}
        <div>
            {{ 'Last update'|trans }}:
            <time class="cursor-help" datetime="{{ region.lastUpdate|date('c') }}" title="{{ region.lastUpdate|format_datetime('medium') }}">{{ region.lastUpdate|ago }}</time>
        </div>
        {% endif %}
    </div>

    {{ include('app/list/table.html.twig') }}

    <div class="text-center mt-3 text-sm text-gray-600">
        <a href="https://osmcha.org/api/v1/aoi/{{ region['osmcha.id'] }}/changesets/feed/" class="flex items-center gap-1">
            <!-- Heroicon name: mini/rss -->
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-4 h-4">
                <path d="M3.75 3a.75.75 0 00-.75.75v.5c0 .414.336.75.75.75H4c6.075 0 11 4.925 11 11v.25c0 .414.336.75.75.75h.5a.75.75 0 00.75-.75V16C17 8.82 11.18 3 4 3h-.25z" />
                <path d="M3 8.75A.75.75 0 013.75 8H4a8 8 0 018 8v.25a.75.75 0 01-.75.75h-.5a.75.75 0 01-.75-.75V16a6 6 0 00-6-6h-.25A.75.75 0 013 9.25v-.5zM7 15a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>

            {{ 'Download OSMCha RSS feed'|trans }}
        </a>
    </div>
</main>

{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {{ encore_entry_link_tags('list') }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('list') }}
{% endblock %}

templates/app/list/map.html.twig
<div id="map-region" class="h-full w-full" data-continent="{{ region.continent }}" data-region="{{ region.key }}"></div>

templates/app/list/table.html.twig
<div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
    <table class="min-w-full divide-y divide-gray-200">
        <thead class="bg-gray-50">
            <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {{ 'Username'|trans }}
                </th>
                <th scope="col" colspan="2"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                </th>
                <th scope="col"
                    class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {{ 'Account created'|trans }}
                </th>
                <th scope="col"
                    class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {{ 'First changeset'|trans }}
                </th>
                <th scope="col" class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {{ 'Changesets'|trans }}
                </th>
                <th scope="col"
                    class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {{ 'Editor'|trans }}
                </th>
                <th scope="col"
                    class="px-6 py-3 text-center text-xs font-medium text-gray-500 uppercase tracking-wider">
                    {{ 'Locale'|trans }}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for mapper in mappers %}

            <tr class="{{ loop.index0 % 2 == 0 ? 'bg-white' : 'bg-gray-50' }} {{ mapper.region|length > 3 ? 'opacity-25 hover:opacity-75' }}">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    {% if app.user is not null %}
                    <a class="shrink-0 group block"
                        href="{{ path('app_mapper_full', {continent: region.continent, regionKey: region.key, id: mapper.id}) }}">
                        {{ include('app/list/avatar.html.twig', {mapper}, with_context=false) }}
                    </a>
                    {% else %}
                    {{ include('app/list/avatar.html.twig', {mapper}, with_context=false) }}
                    {% endif %}
                </td>
                <td class="px-1 py-4 whitespace-nowrap text-center text-sm text-gray-500">
                    <div class="flex flex-col">
                        {% if mapper.welcome.date is defined and mapper.welcome.date is not null %}
                        <span
                            class="h-4 w-4 rounded-full bg-green-500 flex items-center justify-center ring-2 ring-white cursor-help"
                            title="{{ mapper.welcome.date|format_date('long') }}">
                            <!-- Heroicon name: outline/chat -->
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 text-white" fill="none"
                                viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                            </svg>
                        </span>
                        {% endif %}
                        {% if mapper.welcome.reply is defined and mapper.welcome.reply is not null %}
                        <span
                            class="h-4 w-4 rounded-full bg-yellow-400 flex items-center justify-center ring-2 ring-white cursor-help"
                            title="{{ mapper.welcome.reply|format_date('long') }}">
                            <!-- Heroicon name: outline/inbox-in -->
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-3 h-3 text-white" fill="none"
                                viewBox="0 0 24 24" stroke="currentColor">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                    d="M8 4H6a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-2m-4-1v8m0 0l3-3m-3 3L9 8m-5 5h2.586a1 1 0 01.707.293l2.414 2.414a1 1 0 00.707.293h3.172a1 1 0 00.707-.293l2.414-2.414a1 1 0 01.707-.293H20" />
                            </svg>
                        </span>
                        {% endif %}
                    </div>
                </td>
                <td class="px-1 py-4 whitespace-nowrap text-center text-sm text-gray-400">
                    {% if mapper.notes|length > 0 %}
                    <div class="flex items-center">
                        <!-- Heroicon name: outline/document-text -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                        {{ mapper.notes|length }}
                    </div>
                    {% endif %}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500">
                    <time datetime="{{ mapper.accountCreated|date('c') }}">
                        {{ mapper.accountCreated|format_date('long') }}
                    </time>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500">
                    <a class="text-indigo-600 hover:text-indigo-900" target="_blank"
                        href="https://openstreetmap.org/changeset/{{ mapper.firstChangeset.id }}">
                        <time datetime="{{ mapper.firstChangeset.createdAt|date('c') }}">
                            {{ mapper.firstChangeset.createdAt|format_date('long') }}
                        </time>
                    </a>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm text-gray-500">
                    <a class="text-indigo-600 hover:text-indigo-900" target="_blank"
                        href="https://openstreetmap.org/user/{{ mapper.displayName }}/history">
                        {{ mapper.changesetsCount }}
                    </a>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500">
                    {{ mapper.firstChangeset.editor|editor }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-center text-sm text-gray-500">
                    {{ mapper.firstChangeset.locale|replace({'-': '_'})|locale_name }}
                </td>
            </tr>

            {% endfor %}
        </tbody>
    </table>
</div>