src/Entity/Mapper.php
<?php

namespace App\Entity;

use App\Repository\MapperRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MapperRepository::class)]
class Mapper
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    private ?int $id;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $display_name;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $account_created;

    #[ORM\Column(type: 'integer')]
    private ?int $changesets_count;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $status;

    /** @var Collection<int,Changeset> */
    #[ORM\OneToMany(targetEntity: Changeset::class, mappedBy: 'mapper', orphanRemoval: true)]
    private Collection $changesets;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $image;

    /** @var Collection<int,Note> */
    #[ORM\OneToMany(targetEntity: Note::class, mappedBy: 'mapper', orphanRemoval: true)]
    private Collection $notes;

    #[ORM\OneToOne(targetEntity: Welcome::class, mappedBy: 'mapper', cascade: ['persist'])]
    private ?Welcome $welcome;

    /** @var Collection<int,Region> */
    #[ORM\ManyToMany(targetEntity: Region::class, inversedBy: 'mappers')]
    private Collection $region;

    public function __construct()
    {
        $this->changesets = new ArrayCollection();
        $this->notes = new ArrayCollection();
        $this->region = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function setDisplayName(string $display_name): self
    {
        $this->display_name = $display_name;

        return $this;
    }

    public function getAccountCreated(): ?\DateTimeInterface
    {
        return $this->account_created;
    }

    public function setAccountCreated(\DateTimeInterface $account_created): self
    {
        $this->account_created = $account_created;

        return $this;
    }

    public function getChangesetsCount(): ?int
    {
        return $this->changesets_count;
    }

    public function setChangesetsCount(int $changesets_count): self
    {
        $this->changesets_count = $changesets_count;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection<int,Changeset>
     */
    public function getChangesets(): Collection
    {
        return $this->changesets;
    }

    public function addChangeset(Changeset $changeset): self
    {
        if (!$this->changesets->contains($changeset)) {
            $this->changesets[] = $changeset;
            $changeset->setMapper($this);
        }

        return $this;
    }

    public function removeChangeset(Changeset $changeset): self
    {
        // set the owning side to null (unless already changed)
        if ($this->changesets->removeElement($changeset) && $changeset->getMapper() === $this) {
            $changeset->setMapper(null);
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int,Note>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setMapper($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        // set the owning side to null (unless already changed)
        if ($this->notes->removeElement($note) && $note->getMapper() === $this) {
            $note->setMapper(null);
        }

        return $this;
    }

    public function getFirstChangeset(): Changeset
    {
        $changesets = $this->changesets->toArray();

        $createdAt = array_map(static fn (Changeset $changeset): ?\DateTimeImmutable => $changeset->getCreatedAt(), $changesets);

        array_multisort($createdAt, \SORT_ASC, $changesets);

        return $changesets[0];
    }

    public function getWelcome(): ?Welcome
    {
        return $this->welcome;
    }

    public function setWelcome(Welcome $welcome): self
    {
        // set the owning side of the relation if necessary
        if ($welcome->getMapper() !== $this) {
            $welcome->setMapper($this);
        }

        $this->welcome = $welcome;

        return $this;
    }

    /**
     * @return Collection<int, Region>
     */
    public function getRegion(): Collection
    {
        return $this->region;
    }

    public function addRegion(Region $region): self
    {
        if (!$this->region->contains($region)) {
            $this->region->add($region);
        }

        return $this;
    }

    public function removeRegion(Region $region): self
    {
        $this->region->removeElement($region);

        return $this;
    }
}

src/Entity/Template.php
<?php

namespace App\Entity;

use League\CommonMark\Extension\FrontMatter\Data\SymfonyYamlFrontMatterParser;
use League\CommonMark\Extension\FrontMatter\FrontMatterParser;

class Template
{
    private string $name;
    private string $template;
    private string $title;

    public function __construct(
        private string $path,
        private string $locale,
        string $markdown,
    ) {
        $frontMatterParser = new FrontMatterParser(new SymfonyYamlFrontMatterParser());
        $result = $frontMatterParser->parse($markdown);

        $front = $result->getFrontMatter();

        $this->name = $front['name'] ?? ucfirst(basename($this->path, '.md'));
        $this->title = $front['title'] ?? '';

        $this->template = $result->getContent();
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setLocale(string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getLocale(): string
    {
        return $this->locale;
    }

    public function setTemplate(string $template): self
    {
        $this->template = $template;

        return $this;
    }

    public function getTemplate(): string
    {
        return $this->template;
    }

    public function setPath(string $path): self
    {
        $this->path = $path;

        return $this;
    }

    public function getPath(): string
    {
        return $this->path;
    }

    public function getFilename(): string
    {
        return basename($this->path);
    }
}

src/Controller/App/MapperController.php
<?php

namespace App\Controller\App;

use App\Entity\Mapper;
use App\Entity\Note;
use App\Entity\Region;
use App\Entity\Template;
use App\Entity\User;
use App\Entity\Welcome;
use App\Service\RegionsProvider;
use App\Service\TemplatesProvider;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class MapperController extends AbstractController
{
    private Mapper $mapper;

    private ?User $user;

    /** @var Template[] */
    private array $templates;

    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly RegionsProvider $provider,
        private readonly TemplatesProvider $templatesProvider,
    ) {
    }

    #[Route('/{regionKey}/mapper/{id}', name: 'app_mapper', requirements: ['regionKey' => '[\w\-_]+'])]
    #[Route('/{continent}/{regionKey}/mapper/{id}', name: 'app_mapper_full', requirements: ['continent' => 'asia|africa|australia|europe|north-america|south-america', 'regionKey' => '[\w\-_]+'])]
    #[IsGranted('ROLE_USER')]
    public function index(Request $request, string $regionKey, int $id, ?string $continent): Response
    {
        $region = $this->provider->getRegion($continent, $regionKey);

        $this->user = $this->getUser(); // @phpstan-ignore assign.propertyType
        $this->mapper = $this->entityManager->find(Mapper::class, $id);

        $mapperRegions = array_map(fn (Region $region) => $region->getId(), $this->mapper->getRegion()->toArray());

        if (!\in_array($regionKey, $mapperRegions, true)) {
            throw $this->createNotFoundException('This mapper was not detected in this region.');
        }

        // Welcome
        if ($request->query->has('welcome')) {
            $this->updateWelcomeDate($request->query->getBoolean('welcome'));

            return $this->redirectToRoute('app_mapper_full', ['continent' => $continent, 'regionKey' => $regionKey, 'id' => $this->mapper->getId()]);
        }
        if ($request->query->has('reply')) {
            $this->updateWelcomeReply($request->query->getBoolean('reply'));

            return $this->redirectToRoute('app_mapper_full', ['continent' => $continent, 'regionKey' => $regionKey, 'id' => $this->mapper->getId()]);
        }

        // Templates
        $this->templates = $this->templatesProvider->getTemplates($region['key']);
        $template = $this->getDefaultTemplate($request);

        // Notes
        $formNote = $this->note($request);
        if (true === $formNote->isSubmitted() && true === $formNote->isValid()) {
            return $this->redirectToRoute('app_mapper_full', ['continent' => $continent, 'regionKey' => $regionKey, 'id' => $this->mapper->getId()]);
        }

        // Prev/Next mapper
        /** @var Mapper[] */
        $mappers = $this->provider->getEntity($regionKey)?->getMappers()->toArray() ?? [];

        $firstChangetsetCreatedAt = array_map(fn (Mapper $mapper): ?\DateTimeImmutable => $mapper->getFirstChangeset()->getCreatedAt(), $mappers);
        array_multisort($firstChangetsetCreatedAt, \SORT_DESC, $mappers);

        $current = array_search($this->mapper, $mappers, true);
        $prev = $current > 0 ? $mappers[$current - 1] : null;
        $next = $current < (\count($mappers) - 1) ? $mappers[$current + 1] : null;

        return $this->render('app/mapper/index.html.twig', [
            'region' => $region,
            'mapper' => $this->mapper,
            'prev_mapper' => $prev,
            'next_mapper' => $next,
            'changesets' => $this->mapper->getChangesets(),
            'formNote' => $formNote->createView(),
            'templates' => $this->templates,
            'selectedTemplate' => $template,
        ]);
    }

    private function updateWelcomeDate(bool $state): void
    {
        $welcome = $this->mapper->getWelcome();
        if (null === $welcome) {
            $welcome = new Welcome();
            $welcome->setMapper($this->mapper);
        }

        if (true === $state) {
            $welcome->setDate(new \DateTime());
            $welcome->setUser($this->user);

            $this->entityManager->persist($welcome);
        } else {
            $this->entityManager->remove($welcome);
        }

        $this->entityManager->flush();
    }

    private function updateWelcomeReply(bool $state): void
    {
        $welcome = $this->mapper->getWelcome();
        if (null === $welcome) {
            $welcome = new Welcome();
            $welcome->setMapper($this->mapper);
            $welcome->setDate(new \DateTime());
            $welcome->setUser($this->user);
        }
        $welcome->setReply($state ? new \DateTime() : null);

        $this->entityManager->persist($welcome);
        $this->entityManager->flush();
    }

    private function getDefaultTemplate(Request $request): ?Template
    {
        // Get current template based on query
        $templateLocale = $request->query->getAlpha('locale');
        $templateFilename = $request->query->get('template');
        if (null !== $templateFilename && '' !== $templateLocale) {
            $filter = array_filter(
                $this->templates,
                fn (Template $template): bool => substr($template->getLocale(), 0, 2) === substr($templateLocale, 0, 2)
                    && $template->getFilename() === $templateFilename
            );
            if (\count($filter) > 0) {
                return current($filter);
            }
        }

        // Get current template based on mapper locale
        $locale = $this->mapper->getFirstChangeset()->getLocale();
        if (null !== $locale) {
            $filter = array_filter($this->templates, fn (Template $template): bool => substr($template->getLocale(), 0, 2) === substr($locale, 0, 2));
            if (\count($filter) > 0) {
                return current($filter);
            }
        }

        // Take first template
        if (\count($this->templates) > 0) {
            return current($this->templates);
        }

        return null;
    }

    private function note(Request $request): FormInterface
    {
        $note = new Note();
        $note->setMapper($this->mapper);
        $note->setAuthor($this->user);

        $form = $this->createFormBuilder($note)
            ->add('text', TextareaType::class, ['label' => 'Note'])
            ->add('submit', SubmitType::class, ['label' => 'Add'])
            ->getForm();

        $form->handleRequest($request);

        if (true === $form->isSubmitted() && true === $form->isValid()) {
            $note->setDate(new \DateTime());

            $this->entityManager->persist($note);
            $this->entityManager->flush();
        }

        return $form;
    }
}

templates/app/mapper/form.html.twig
<section aria-labelledby="applicant-information-title">
    <div class="bg-white shadow sm:rounded-lg">
        <div class="border-b border-gray-200 px-4 py-5 sm:px-6">
            <h2 id="applicant-information-title" class="text-lg leading-6 font-medium text-gray-900">
                {{ 'Send a welcome message'|trans }}
            </h2>
        </div>

        <div class="flex gap-4 p-4">
            <nav aria-label="Sidebar">
                <div>
                    <h3 class="px-3 text-xs font-semibold text-gray-500 uppercase tracking-wider"
                        id="projects-headline">
                        {{ 'Templates'|trans }}
                    </h3>
                    <div class="mt-1 space-y-1" aria-labelledby="projects-headline">
                        {% for template in templates %}
                        <!-- Current: "bg-gray-100 text-gray-900", Default: "text-gray-600 hover:bg-gray-50 hover:text-gray-900" -->
                        {% set active = template == selectedTemplate %}
                        <a class="group flex items-center px-3 py-2 text-sm font-medium rounded-md {{ active ? 'bg-gray-100 text-gray-900' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50' }}"
                            href="{{ path('app_mapper_full', {continent: region.continent, regionKey: region.key, id: mapper.id}) }}?locale={{ template.locale }}&amp;template={{ template.filename }}">
                            <span class="truncate">
                                {{ template.name }} ({{ template.locale|language_name }})
                            </span>
                        </a>

                        {% endfor %}
                    </div>
                </div>
            </nav>

            <form class="w-full" id="template-form" autocomplete="off" data-mapper="{{ mapper.displayName }}">
                <div class="my-2 sm:mt-0 sm:col-span-2">
                    <input type="text" name="title" id="template-title" value="{{ selectedTemplate is not null ? selectedTemplate.title }}"
                        class="p-2 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-300 rounded-md text-gray-500">
                </div>

                <div class="min-h-72 h-72 w-full p-2 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border border-gray-300 rounded-md editor language-markdown">
                    {{- selectedTemplate is not null ? include(template_from_string(selectedTemplate.template)) -}}
                </div>
                <div class="flex justify-between pt-4">
                    <button
                        class="inline-flex items-center justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500"
                        type="button" id="template-copy">
                        <!-- Heroicon name: outline/clipboard -->
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24"
                            stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                        </svg>
                        {{ 'Copy text to clipboard'|trans }}
                    </button>
                    <button
                        class="px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                        type="submit" id="template-send">{{ 'Load message in osm.org'|trans }}</button>
                </div>
            </form>
        </div>
    </div>
</section>

templates/app/mapper/header.html.twig
<div class="max-w-3xl mx-auto md:flex md:items-center md:justify-between md:space-x-5 lg:max-w-7xl">
    <div class="flex items-center space-x-5">
        <div class="shrink-0">
            <div class="relative">
                {% if mapper.image is not null %}
                <img class="h-16 w-16 rounded-full border" src="{{ mapper.image }}"
                    alt="{{ mapper.displayName }} profile picture">
                {% else %}
                <img class="h-16 w-16 rounded-full border" src="{{ asset('build/images/avatar_large.png') }}"
                    alt="Default profile picture">
                {% endif %}
                <span class="absolute inset-0 shadow-inner rounded-full" aria-hidden="true"></span>
            </div>
        </div>
        <div>
            <h1 class="text-2xl font-bold text-gray-900">{{ mapper.displayName }}</h1>
            <p class="text-sm font-medium text-gray-500">
                {% set date = mapper.accountCreated|format_date('long') %}
                {{ 'Mapper since {date}'|trans({'{date}': date}) }}
            </p>
            <p class="text-sm font-medium text-gray-500">
                {{ 'Mapper detected in {count} region(s)'|trans({'{count}': mapper.region|length}) }}
            </p>
        </div>
    </div>
    <div class="mt-6 flex flex-col-reverse justify-stretch space-y-4 space-y-reverse sm:flex-row-reverse sm:justify-end sm:space-x-reverse sm:space-y-0 sm:space-x-3 md:mt-0 md:flex-row md:space-x-3">
        <a class="inline-flex items-center justify-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            target="_blank" href="https://www.openstreetmap.org/user/{{ mapper.displayName }}">
            {{ 'Profile'|trans }}
        </a>
        <a class="inline-flex items-center justify-center px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500"
            title="How did you contribute to OpenStreetMap?" target="_blank" href="https://hdyc.neis-one.org/?{{ mapper.displayName }}">
            HDYC
        </a>

        <span class="relative z-0 inline-flex shadow-sm rounded-md">
            <a class="{{ prev_mapper is null ? 'opacity-50 cursor-default' : '' }} relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                href="{{ prev_mapper is null ? '#' : path('app_mapper_full', {continent: region.continent, regionKey: region.key, id: prev_mapper.id}) }}"
                title="{{ prev_mapper is null ? '' : prev_mapper.displayName }}">
                <span class="sr-only">{{ 'Previous mapper'|trans }}</span>
                <!-- Heroicon name: solid/chevron-left -->
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                    aria-hidden="true">
                    <path fill-rule="evenodd"
                        d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                        clip-rule="evenodd" />
                </svg>
            </a>
            <a class="-ml-px {{ next_mapper is null ? 'opacity-50 cursor-default' : '' }} relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm font-medium text-gray-500 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
                href="{{ next_mapper is null ? '#' : path('app_mapper_full', {continent: region.continent, regionKey: region.key, id: next_mapper.id}) }}"
                title="{{ next_mapper is null ? '' : next_mapper.displayName }}">
                <span class="sr-only">{{ 'Next mapper'|trans }}</span>
                <!-- Heroicon name: solid/chevron-right -->
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                    aria-hidden="true">
                    <path fill-rule="evenodd"
                        d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                        clip-rule="evenodd" />
                </svg>
            </a>
        </span>
    </div>
</div>

templates/app/mapper/timeline.html.twig
<section class="bg-white px-4 py-5 shadow sm:rounded-lg sm:px-6">
    <h2 id="timeline-title" class="text-lg font-medium text-gray-900">{{ 'Timeline'|trans }}</h2>

    <!-- Activity Feed -->
    <div class="mt-6 flow-root">
        <ul class="-mb-8">

            {% if mapper.welcome.reply is defined and mapper.welcome.reply is not null %}
            <li>
                <div class="relative pb-8">
                    <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
                    <div class="relative flex space-x-3">
                        <div>
                            <span
                            class="h-8 w-8 rounded-full bg-yellow-400 flex items-center justify-center ring-8 ring-white">
                                <!-- Heroicon name: outline/inbox-in -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M8 4H6a2 2 0 00-2 2v12a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-2m-4-1v8m0 0l3-3m-3 3L9 8m-5 5h2.586a1 1 0 01.707.293l2.414 2.414a1 1 0 00.707.293h3.172a1 1 0 00.707-.293l2.414-2.414a1 1 0 01.707-.293H20" />
                                </svg>
                            </span>
                        </div>
                        <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                            <div>
                                <p class="text-sm text-gray-500">
                                    {% set userlink = '<a class="font-medium text-gray-900" target="_blank" href="https://www.openstreetmap.org/user/' ~ mapper.displayName ~ '">' ~ mapper.displayName ~ '</a>' %}
                                    {{ '{userlink} has replied'|trans({'{userlink}': userlink})|raw }}
                                </p>
                            </div>
                            <div class="text-right text-sm whitespace-nowrap text-gray-500">
                                <time datetime="{{ mapper.welcome.reply|date('c') }}">
                                    {{ mapper.welcome.reply|format_date('medium') }}
                                </time>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            {% endif %}

            {% if mapper.welcome.date is defined and mapper.welcome.date is not null %}
            <li>
                <div class="relative pb-8">
                    <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
                    <div class="relative flex space-x-3">
                        <div>
                            <span
                                class="h-8 w-8 rounded-full bg-green-500 flex items-center justify-center ring-8 ring-white">
                                <!-- Heroicon name: outline/chat -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                                </svg>
                            </span>
                        </div>
                        <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                            <div>
                                <p class="text-sm text-gray-500">
                                    {% set userlink = '<a class="font-medium text-gray-900" target="_blank" href="https://www.openstreetmap.org/user/' ~ mapper.welcome.user.displayName ~ '">' ~ mapper.welcome.user.displayName ~ '</a>' %}
                                    {{ 'Welcomed by {userlink}'|trans({'{userlink}': userlink})|raw }}
                                </p>
                            </div>
                            <div class="text-right text-sm whitespace-nowrap text-gray-500">
                                <time datetime="{{ mapper.welcome.date|date('c') }}">
                                    {{ mapper.welcome.date|format_date('medium') }}
                                </time>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            {% endif %}

            {% for changeset in changesets|sort((a, b) => a.createdAt <=> b.createdAt)|reverse %}
            <li>
                <div class="relative pb-8">
                    <span class="absolute top-4 left-4 -ml-px h-full w-0.5 bg-gray-200" aria-hidden="true"></span>
                    <div class="relative flex space-x-3">
                        <div>
                            <span
                                class="h-8 w-8 rounded-full bg-blue-500 flex items-center justify-center ring-8 ring-white">
                                <!-- Heroicon name: outline/pencil -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                        d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                                </svg>
                            </span>
                        </div>
                        <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                            <div>
                                <p class="text-sm text-gray-500">
                                    {{ 'Changeset'|trans }}
                                    <a class="font-medium text-gray-900" target="_blank" href="https://www.openstreetmap.org/changeset/{{ changeset.id }}">
                                        #{{ changeset.id }}
                                    </a>
                                </p>
                            </div>
                            <div class="text-right text-sm whitespace-nowrap text-gray-500">
                                <time datetime="{{ changeset.createdAt|date('c') }}">
                                    {{ changeset.createdAt|format_date('medium') }}
                                </time>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            {% endfor %}

            <li>
                <div class="relative pb-8">
                    <div class="relative flex space-x-3">
                        <div>
                            <span
                                class="h-8 w-8 rounded-full bg-gray-400 flex items-center justify-center ring-8 ring-white">
                                <!-- Heroicon name: solid/user -->
                                <svg class="w-5 h-5 text-white" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                                    fill="currentColor" aria-hidden="true">
                                    <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z"
                                        clip-rule="evenodd" />
                                </svg>
                            </span>
                        </div>
                        <div class="min-w-0 flex-1 pt-1.5 flex justify-between space-x-4">
                            <div>
                                <p class="text-sm text-gray-500">{{ 'Account created'|trans }}</p>
                            </div>
                            <div class="text-right text-sm whitespace-nowrap text-gray-500">
                                <time datetime="{{ mapper.accountCreated|date('c') }}">
                                    {{ mapper.accountCreated|format_date('medium') }}
                                </time>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</section>